[package]
name = "gook_zzang_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.18", features = ["macros","rt-multi-thread"] }

[dependencies.serenity]
default-features = false
features = ["client", "gateway", "model", "rustls_backend"]
version = "0.11"